---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(jsonlite)
library(tidyverse)
```

```{r}
demo_table <- read.csv(file="demo.csv",check.names=F,stringsAsFactors = F )
```

```{r}
demo_table2 <-fromJSON(txt='demo.json')
```

```{r}
# Select the third row of the Year column
demo_table[3,"Year"]
```
```{r}
#Year is column 3. So we can do the same with the following code
demo_table[3,3]
```
```{r}
# Select column "Vehicle_Class" from demo_table
demo_table$Vehicle_Class
```
```{r}
# Select row 2 from Vehicle_Class from demo_table
demo_table$Vehicle_Class[2]
```
```{r}
# Filter demo_table2 for price greater than 10000
filter_table <- demo_table2[demo_table2$price>=10000,]
```

```{r}
# This can be done through this alternate code
filter_table2 <- filter(demo_table2, price>=10000)
```

```{r}
filter_table3 <- subset(demo_table2, price > 10000 & drive == "4wd" & title_status =="clean")
```

```{r}
# The same code can be done using the filter function
filter_table4 <- filter(demo_table2, price > 10000 & drive == "4wd" & title_status =="clean")
```

```{r}
# We will add two columns to a data-set using mutate. We will write using the pipe method
demo_table <- demo_table %>% mutate(Mileage_per_Year = Total_Miles/(2000-Year), Is_Active=TRUE)
```

```{r}
# Group cars by condition and determine the average mileage per condition
summarize_demo <- demo_table2 %>% group_by(condition) %>% summarize(Mean_Mileage = mean(odometer))
```

```{r}
# This can be done without using pipe method
group_demo <- group_by(demo_table2, condition)
summarize_demo1 <- summarize(group_demo, Mean_Mileage = mean(odometer))
```

```{r}
# Group cars by condition and determine the average mileage per condition, maximum price per condition and number of vehicles per condition
summarize_demo2 <- demo_table2 %>% group_by(condition) %>% summarize(Mean_Mileage = mean(odometer), Maximum_Price = max(price), Num_Vehicles=n())
```

```{r}
demo_table3 <- read.csv('demo2.csv',check.names = F,stringsAsFactors = F)
```

```{r}
long_table <- gather(demo_table3,key="Metric",value="Score",buying_price:popularity)
```

```{r}
wide_table <- long_table %>% spread(key="Metric",value="Score")
```

```{r}
# Import data-set into ggplot2
plt <- ggplot(mpg, aes(x=class))
# plot a bar plot
plt + geom_bar()
```
```{r}
# We will summarize the data by manufacturer and count the numbers in each category of manufacturer
mpg_summary <- mpg %>% group_by(manufacturer) %>% summarise(Vehicle_Count=n())
# We will visualize this using gggplot2. Import data-set into ggplot2
plt1 <- ggplot(mpg_summary, aes(x=manufacturer, y=Vehicle_Count))
plt1 <- ggplot(mpg_summary,aes(x=manufacturer,y=Vehicle_Count))
# plot a bar plot
plt1 + geom_col() + xlab("Manufacturing Company") + ylab("Number of Vehicles in Dataset") +
theme(axis.text.x=element_text(angle=45,hjust=1)) 
```
```{r}
# Compare fuel economy (hwy) if Toyota as a function of different cylinder sizes
# First we create a summary table
mpg_summary <- subset(mpg,manufacturer=="toyota") %>% group_by(cyl) %>% summarize(Mean_Hwy=mean(hwy))
#import data-set into ggplot2
plt2 <- ggplot(mpg_summary,aes(x=cyl,y=Mean_Hwy)) 
# generate line plot. 
plt2 + geom_line()
```
```{r}
# We will make the x-axis discrete and y-axis continous
plt2 + geom_line() + scale_x_discrete(limits=c(4,6,8)) + scale_y_continuous(breaks = c(15:30))
```
```{r}
# scatter plot to show size of each car engine (displ) versus their city fuel efficiency (cty)
plt3 <- ggplot(mpg, aes(x=displ,y=cty))
plt3 + geom_point() + xlab("Engine Size (L)") + ylab("City Fuel-Efficiency (MPG)")
```
```{r}
plt3 <- ggplot(mpg, aes(x=displ, y=cty, color=class))
plt3 + geom_point() + labs(x="Engine Size (L)", y="City Fuel-Efficiency (MPG)", color="Vehicle Class")
```
```{r}
plt4 <- ggplot(mpg,aes(y=hwy)) 
plt4 + geom_boxplot()
```
```{r}
plt5 <- ggplot(mpg,aes(x=manufacturer,y=hwy))
plt5 + geom_boxplot() + theme(axis.text.x=element_text(angle=45,hjust=1))
```
```{r}
# Summary table for average highway fuel efficiency across vehicle class from 1999 to 2008
mpg_summary1 <- mpg %>% group_by(class,year) %>% summarize(Mean_Hwy=mean(hwy)) 
plt6 <- ggplot(mpg_summary1, aes(x=class,y=factor(year),fill=Mean_Hwy))
#create heatmap with labels
plt6 + geom_tile() + labs(x="Vehicle Class",y="Vehicle Year",fill="Mean Highway (MPG)") 

```
```{r}
# Summary table for average highway fuel efficiency across vehicle model from 1999 to 2008
mpg_summary2 <- mpg %>% group_by(model,year) %>% summarize(Mean_Hwy=mean(hwy))
plt7 <- ggplot(mpg_summary2, aes(x=model,y=factor(year),fill=Mean_Hwy))
#add heat map with labels and rotate x-axis labels 90 degrees
plt7 + geom_tile() + labs(x="Model",y="Vehicle Year",fill="Mean Highway (MPG)") +   theme(axis.text.x = element_text(angle=90,hjust=1,vjust=.5)) 
```
```{r}
# Here we are overlaying a scatter plot on top of a box plot using the same data
plt8 <- ggplot(mpg,aes(x=manufacturer,y=hwy)) 
plt8 + geom_boxplot() + theme(axis.text.x=element_text(angle=45,hjust=1)) +  
geom_point()
```
```{r}
# Scatter plot to compare average engine size (displ) for each class 
mpg_summary3 <- mpg %>% group_by(class) %>% summarize(Mean_Engine=mean(displ), ,SD_Engine=sd(displ))
plt9 <- ggplot(mpg_summary3,aes(x=class,y=Mean_Engine))
# Scatter plot with overlay of standard deviation
plt9 + geom_point(size=3) + labs(x="Vehicle Class",y="Mean Engine Size") + 
  geom_errorbar(aes(ymin=Mean_Engine-SD_Engine,ymax=Mean_Engine+SD_Engine))
```

```{r}
#import used car dataset
population_table <- read.csv('used_car_data.csv',check.names = F,stringsAsFactors = F) 
```

```{r}
#import data-set into ggplot10 and generate the density plot
plt10 <- ggplot(population_table,aes(x=Miles_Driven)) 
plt10 + geom_density()
```
```{r}
#import data-set into ggplot10 and generate the density plot
plt11 <- ggplot(population_table,aes(x=log10(Miles_Driven))) 
plt11 + geom_density()
```
ˆ
```{r}
#randomly sample 50 data points
sample_table <- population_table %>% sample_n(50) 
#import data set into ggplot2 and visualize the distribution using a density plot
plt <- ggplot(sample_table,aes(x=log10(Miles_Driven)))
plt + geom_density()
```
```{r}
# Perform a T-test to compare sample versus population
t.test(log10(sample_table$Miles_Driven),mu=mean(log10(population_table$Miles_Driven))) 
```
```{r}
## WE ARE NOW SWITCHING TO PAIRED T-TESTS

mpg_data <- read.csv('mpg_modified.csv') #import data set
```
```{r}
#select only data points where the year is 1999
mpg_1999 <- mpg_data %>% filter(year==1999) 
#select only data points where the year is 2008
mpg_2008 <- mpg_data %>% filter(year==2008) 
```
```{r}
#compare the mean difference between two samples
t.test(mpg_1999$hwy, mpg_2008$hwy,paired = T) 
```

```{r}
## WE ARE NOT SWITCHING TO ANOVA TESTS

#filter columns from mtcars data set
mtcars_filt <- mtcars[,c("hp","cyl")]


## This additional step was required because in the MT cars data set the 
## cyl variable as numerical and not categorical. Therefore we had to convert
## the numerical column to a factor
#convert numeric column to factor
mtcars_filt$cyl <- factor(mtcars_filt$cyl) 
```
```{r}
#compare means across multiple levels
aov(hp ~ cyl,data=mtcars_filt) 
```
```{r}
# Wrap aov function in a summary function
summary(aov(hp ~ cyl,data=mtcars_filt))
```

```{r}
## WE ARE NOW MOVING ON TO REGRESSION

head(mtcars)
```
```{r}
# Import data set into ggplot2 and create a scatter plot
ggplot(mtcars,aes(x=hp,y=qsec)) + geom_point()
```
```{r}
#calculate correlation coefficient
cor(mtcars$hp,mtcars$qsec) 
```
```{r}
# We are using the used_car_data.csv file again
# It should be noted that the population_table vector and 
#   used car vectors are the same. The module just asks us to import it
#   twice and name it separate vectors for separate uses. 
used_cars <- read.csv('used_car_data.csv',stringsAsFactors = F)
head(used_cars)
```
```{r}
# Import data set into ggolot 2 and create a scatter plot
ggplot(used_cars,aes(x=Miles_Driven,y=Selling_Price)) + geom_point()
```
```{r}
# calculate the correlation coefficient
cor(used_cars$Miles_Driven,used_cars$Selling_Price)
```
```{r}
# This correlation matrix can be used to get correlations for multiple variables
used_matrix <- as.matrix(used_cars[,c("Selling_Price","Present_Price","Miles_Driven")])
cor(used_matrix)
```

```{r}
# This is a single regression to check for correlation between horse power and quarter second mile

#create linear model
lm(qsec ~ hp,mtcars) 
```
```{r}
#summarize linear model
summary(lm(qsec~hp,mtcars)) 
```
```{r}
#create linear model
model <- lm(qsec ~ hp,mtcars) 
#determine y-axis values from linear model
yvals <- model$coefficients['hp']*mtcars$hp +
model$coefficients['(Intercept)'] 

#import data set into ggplot2 and plot the scatter and linear model
ggplot(mtcars,aes(x=hp,y=qsec)) + geom_point() + geom_line(aes(y=yvals), color = "red")
```

```{r}
# We will not move to multiple lenear regression where we look at correlation between mutliple factors
#generate multiple linear regression model
lm(qsec ~ mpg + disp + drat + wt + hp,data=mtcars) 
```
```{r}
#generate summary statistics
summary(lm(qsec ~ mpg + disp + drat + wt + hp,data=mtcars)) 
```













